---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cel-expr-pr-
  annotations:
    # pipelinesascode.tekton.dev/on-event: "[pull_request]"
    # pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-label: "[bug]"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && (".tekton/pipelinerun.yaml".pathChanged() || "main.go".pathChanged() || "go.{mod,sum}".pathChanged())
spec:
  params:
    - name: body
      value: |
        {{ body }}
  pipelineSpec:
    params:
      - name: body
    tasks:
      - name: noop-task
        displayName: Task with no effect
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                echo "Labels on PR: "
                for i in $(echo -e "{{ labels }}");do
                  echo $i
                done
                exit 0
